apiVersion: apps/v1
kind: Deployment
metadata:
  name: express-hello-world
  namespace: express-hello-world
spec:
  replicas: 2
  selector:
    matchLabels:
      app: express-hello-world
  template:
    metadata:
      labels:
        app: express-hello-world
    spec:
      containers:
        - image: ecarlste/express-hello-world:0.1.8
          name: express-hello-world
          ports:
            - containerPort: 3000
